### ISSUE TITLE
Error: Check simulated residuals for NA values

### ISSUE THREAD

**Issue by Jason-Conner-NOAA** [James-Thorson/FishStatsUtils#73] opened 2021-05-27 18:04 UTC
From line 511 in fit_model().

Running Pacific cod age composition for 2021 and get this message.

Can you give some guidance on what I can do to resolve the NAs? I can provide the fit object, if it helps.

Cheers!

**Comment by James-Thorson-NOAA** [comment] 2021-05-27 18:11
Thanks for asking!  can you try running with `plot(fit, check_residuals = FALSE, ...)` and confirm that it works when turning off residuals?

**Comment by Jason-Conner-NOAA** [comment] 2021-05-27 18:23
Yes, turning off residuals lets plot() complete.

**Comment by James-Thorson-NOAA** [comment] 2021-05-27 18:25
OK thanks. I've wanted to dig into this error for a while ... it arises in a small proportion of cases, using the simulation-residuals (which are much better than the previous Pearson residuals).

are you doing an index model, or full comps?  I think the next step is finding a reproducible example for me to explore, and I'd love for it to not be a full comps run.

**Comment by Jason-Conner-NOAA** [comment] 2021-05-27 18:27
This is for comps, 13 age categories. 24 hours to run :/

**Comment by Jason-Conner-NOAA** [comment] 2021-05-27 18:30
This example gives me 722500 NAs in the b_iz matrix (dim = 125905    250).

**Comment by James-Thorson-NOAA** [comment] 2021-05-30 17:14
I fixed a problem that resembles the one you flagged.  The fix arises because `DHARMa` (for reasons I don't understand or think is necessary) applies a smoother to PIT residuals somewhere internally, and I'm guessing this causes a problem for observations where all simulations give a value of 0.  However, I don't use the DHARMa PIT calculations anyway (I replace their calculation with my own in VAST).  So I can avoid the problem by setting DHARMa to do their `method="tranditional"` calculation prior to replacing the values with PIT residuals.

Anyhoo, the `dev` branch of FishStatsUtils has that change, which fixes an instance of this error on a simpler example.  I'm guessing we'll want to email a bit to decide how to proceed.  It seems like our two options are:

1. Turn off residual calculations for stocks where this problem arises, and upgrade the version for 2022 so that the problem is fixed next year.
2. Upgrade VAST/FishStatsUtils to the dev branch for now, either just for stocks where this arises, or for all AFSC stocks.

I recommend option 1, but imagine we'll want to discuss.

**Comment by James-Thorson-NOAA** [comment] 2021-05-31 21:41
After further investigating, I confirmed that the problem arose in the version of `DHARMa` mirrored on the MRAN 4.0.2 server, and which was fixed on CRAN subsequently but not on MRAN because they use a static mirror from time of release.  I have fixed the issue manually in VAST (somewhat redundantly), and users can also avoid the issue without updating VAST by simply manually updating `DHARMa` to the newest numeric release, e.g., [0.4.0](https://github.com/florianhartig/DHARMa/releases/tag/v0.4.0)

**Closed as completed by James-Thorson-NOAA** 2021-05-31 21:41 UTC

**Comment by Jason-Conner-NOAA** [comment] 2021-08-04 15:58
Returning to this topic, I am unable to run residuals (same error as original) in the following environments:
Unchanged versions: VAST 3.6.1 FishStatsUtils 2.8.0
MRAN 4.0.2
R 4.0.2
DHARMa 0.4.0, 0.4.3, 0.4.3.1

Tried the dev branch of FishStatsUtils (2.10.0) which resulted in a different error, I assume from building the model with VAST 3.6.1:
Error in UseMethod("units") : 
  no applicable method for 'units' applied to an object of class "c('double', 'numeric')"

**Comment by James-Thorson-NOAA** [comment] 2021-08-04 16:01
OK the development branch is switching to use package `units`, let's skip that for now.

Can you clarify what exactly is the terminal output in the error you're having with residuals?  I don't remember the details above in this thread except that I tracked down and solved a prior issue.

**Comment by Jason-Conner-NOAA** [comment] 2021-08-04 16:23
### Making quantile residuals using conditional simulation and package DHARMa
Sampling from the distribution of data conditional on estimated fixed and random effects
  Finished sample 25 of 250
  Finished sample 50 of 250
  Finished sample 75 of 250
  Finished sample 100 of 250
  Finished sample 125 of 250
  Finished sample 150 of 250
  Finished sample 175 of 250
  Finished sample 200 of 250
  Finished sample 225 of 250
  Finished sample 250 of 250
Error in summary.fit_model(fit, what = "residuals", working_dir = working_dir,  : 
  Check simulated residuals for NA values

> traceback()
4: stop("Check simulated residuals for NA values")
3: summary.fit_model(fit, what = "residuals", working_dir = working_dir, 
       type = type, ...)
2: summary(fit, what = "residuals", working_dir = working_dir, type = type, 
       ...)
1: plot_results(fit, zrange = c(-3, 3), n_cells = 600, strata_names = strata_names, 
       check_residuals = TRUE, n_samples = 0)

**Comment by Jason-Conner-NOAA** [comment] 2021-08-19 15:19
Confirmed that this error was due to NAs in b_i of the input data.

**Comment by James-Thorson-NOAA** [comment] 2021-08-19 15:27
Thanks Jason!

The dev branch now has a fix for those cases that include `NAs` in the input `b_i` ... it just changes those samples and their predictive distribution to a vector of zeros for purposes of calculating PIT residuals visualized using DMARMa, which will then have a standard-uniform distribution for residuals.
